export const orders = [
    {
        idOrden: 1,
        idMesa: 1,
        idComida: 1,
        nombreComida: "Brownie",
        nombreCategoria: "Postre",
        precio: 15,
        cantidad: 2,
        fechaCreacion: "2022-06-24T13:00:00",
        estadoOrden: "Pendiente",
        saved: true,
    },
    {
        idOrden: 2,
        idMesa: 1,
        idComida: 1,
        nombreComida: "Brownie",
        nombreCategoria: "Postre",
        precio: 15,
        cantidad: 2,
        fechaCreacion: "2022-06-24T13:00:00",
        estadoOrden: "Pendiente",
        saved: true,
    },
    {
        idOrden: 3,
        idMesa: 1,
        idComida: 1,
        nombreComida: "Brownie",
        nombreCategoria: "Postre",
        precio: 15,
        cantidad: 2,
        fechaCreacion: "2022-06-24T13:00:00",
        estadoOrden: "Pendiente",
        saved: true,
    },
    {
        idOrden: 4,
        idMesa: 1,
        idComida: 1,
        nombreComida: "Brownie",
        nombreCategoria: "Postre",
        precio: 15,
        cantidad: 2,
        fechaCreacion: "2022-06-24T13:00:00",
        estadoOrden: "Pendiente",
        saved: true,
    },
];