export const orders = [
  {
    idOrden: 1,
    idMesa: 1,
    idComida: 1,
    nombreComida: 'Brownie',
    idPedido: '',
    nombreCategoria: 'Postre',
    precio: 15,
    cantidad: 2,
    fechaCreacion: new Date(),
    estadoOrden: 'Pendiente',
    saved: true,
  },
  {
    idOrden: 2,
    idPedido: '',
    idMesa: 1,
    idComida: 1,
    nombreComida: 'Keke',
    nombreCategoria: 'Postre',
    precio: 15,
    cantidad: 2,
    fechaCreacion: new Date(),
    estadoOrden: 'Pendiente',
    saved: true,
  },
  {
    idOrden: 3,
    idMesa: 1,
    idComida: 1,
    idPedido: '',
    nombreComida: 'Chiscake',
    nombreCategoria: 'Postre',
    precio: 15,
    cantidad: 2,
    fechaCreacion: new Date(),
    estadoOrden: 'Pendiente',
    saved: true,
  },
  {
    idOrden: 4,
    idMesa: 1,
    idComida: 1,
    nombreComida: 'Cachitos',
    nombreCategoria: 'Postre',
    precio: 15,
    cantidad: 2,
    fechaCreacion: new Date(),
    estadoOrden: 'Pendiente',
    saved: true,
    idPedido: '',
  },
];
